# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nGRHFPAFVYogPrOZBA2MnN7tQyJnt7wZ

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"
s.split()

"""*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("The diameter of "+format(planet)+" is "+format(diameter)+ " kilometers.")

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
a=np.zeros(10)
a

import numpy as np
a=np.ones(10)*5
a

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
b=np.arange(20,36,2)

b

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

c=np.arange(9).reshape(3,3)
c

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd
import numpy as np
A=np.random.randint(10,size=(3,2))

A

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd
import numpy as np
df = pd.DataFrame()
start_date = '2023-01-01'
end_date = '20213-02-10'
# Select DataFrame rows between two dates
mask = (df['Jan'] > start_date) & (df['Feb'] <= end_date)
df2 = df.loc[mask]
print(df2)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns = ['Index', 'letter','num'])

df